import esbuild from 'esbuild';
import process from 'process';

// 社区插件约定：构建产物顶部加这段声明，方便审核者确认 main.js 是打包产物而非手写源码
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the GitHub repository of this plugin
*/
`;

// 用法：
//   node esbuild.config.mjs             → watch 模式（可读输出，开发用）
//   node esbuild.config.mjs once        → 构建一次（可读输出，便于人工审阅）
//   node esbuild.config.mjs production  → 构建一次（压缩，发布用）
const mode = process.argv[2];
const production = mode === 'production';
const once = production || mode === 'once';

// obsidian / electron 由运行时提供，必须标为 external，否则会被打进包里导致加载失败
const external = [
  'obsidian',
  'electron',
  '@codemirror/autocomplete',
  '@codemirror/collab',
  '@codemirror/commands',
  '@codemirror/language',
  '@codemirror/lint',
  '@codemirror/search',
  '@codemirror/state',
  '@codemirror/view',
  '@lezer/common',
  '@lezer/highlight',
  '@lezer/lr',
  'assert',
  'buffer',
  'child_process',
  'crypto',
  'events',
  'fs',
  'http',
  'https',
  'net',
  'os',
  'path',
  'process',
  'punycode',
  'querystring',
  'stream',
  'string_decoder',
  'timers',
  'tls',
  'url',
  'util',
  'vm',
  'zlib',
];

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external,
  format: 'cjs', // Obsidian 以 CommonJS 方式加载 main.js
  target: 'es2018',
  platform: 'browser',
  logLevel: 'info',
  sourcemap: false,
  treeShaking: true,
  minify: production,
  outfile: 'main.js',
});

if (once) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
